language: node_js

node_js:
  - "6"

matrix:
  include:
    - os: linux
      env: ARCH=ia32
    - os: linux
      env: ARCH=x64
    - os: linux
      env: ARCH=armv7l
    - os: osx

cache:
  directories:
  - node_modules
  - "$HOME/.electron"

addons:
  apt:
    packages:
    - rpm

install:
  - npm install npm -g
  - npm install
  - npm prune

before_script:
  # Trigger packaging by ourselves to define the target architecture
  - if [[ -v ARCH ]]; then  electron-forge package --arch=$ARCH  ; fi

script:
  - npm run build

# Display folder structure to see all build files.
#after_script:
#  - echo "files in folder 'out/make/'"
#  - find out/make/ -exec ls -dl \{\} \; | awk '{print $3, $4, $9}'

deploy:
  skip_cleanup: true
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file:
    - out/make/mac/*.zip
    - out/make/mac/*.dmg
    - out/make//*.zip
    - out/make//*.dmg
    - out/make/*.deb
    - out/make/*.rpm
    - out/make/*.zip
  # releases created by travis are created as prerelease and are manually approved
  prerelease: true
  on:
    repo: Bruce17/electron-test
    tags: true
